name: vania
description: vania
version: 0.0.1
#homepage: 
#repository: 
#issue_tracker: 
#documentation: 
#topics: [server, backend, httpserver]

#screenshots:
#  - description: 'Vania logo.'
#    path: assets/logo.png

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.12.2
  eloquent: ^3.0.0
  meta: ^1.11.0
  mime: ^1.0.5
  path: ^1.9.0
  sprintf: ^7.0.0
  string_scanner: ^1.2.0
  uuid: ^4.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  http: ^1.2.0
  http_parser: ^4.0.2
